[package]
name = "dit"
version = "0.1.0-pre"
edition = "2018"

[dependencies]
anyhow = "1.0.42"
clap = "3.0.0-beta.4"
env_logger = "0.9.0"
format = "0.2.4"
lifetime = { version = "0.1.0", features = ["macros"] }
log = "0.4.14"
serde = { version = "1.0.128", features = ["derive"] }
thiserror = "1.0.26"
toml = { version = "0.5.8" }
url = "2.2.2"
xdg = { version = "2.2.0", git = "https://github.com/ErichDonGubler/rust-xdg", branch = "windows-support" }
