[licenses]
allow = [
	"Apache-2.0",
	"CC0-1.0",
	"LGPL-3.0",
	"MIT",
	"MPL-2.0",
	"Unicode-DFS-2016",
	"Unicode-3.0",
]
exceptions = [
	# This is us! We don't automatically `allow` GPL-3.0 by default because
	# that requires some extra work to integrate correctly.
	{ name = "bellboy", allow = ["GPL-3.0"] },
]
